### ISSUE TITLE
_transient_states_indices really slow for large state numbers

### ISSUE THREAD

**Issue by Marius1311** [TommasoBelluzzo/PyDTMC#3]
## Description
I'm trying to run the package on a relatively large number of states (~2000) and I have realised that calling self._transient_states_indices runs extremly slow (I waited several minutes and interrupted it then). Is there any possibility to speed it up?

## Motivation and Context
I think this is a bottleneck for large MCs as many other functions use this property

**Comment by TommasoBelluzzo** [comment]
I never tested the framework with such big chains, that's why I never noticed this problem before. 2000 states represent a huge volume of indices to handle... but Python should be able to do it without performance issues. I suppose the current sorting approach is not the right one to use, so I'll start testing other approaches to achieve the same result. Your suggestions are more than welcome.

**Comment by Marius1311** [comment]
Thanks! One possibility would be to use sparse matrixes, that should speed up computations considerably.

**Comment by TommasoBelluzzo** [comment]
This would implicitly require a huge rewriting process concerning the whole script. Something I could undertake in a near future but I was looking for a short term, quick and dirty, solution rigjt now.

**Comment by Marius1311** [comment]
alright, sounds good!

**Comment by TommasoBelluzzo** [comment]
Ok, after a few tests (today I performed a code cleanup and pushed a new version on PyPI) I discovered the real bottleneck comes from the computation of classes for very big matrices (_recurrent_classes_indices and _transient_classes_indices are mainly involved). Implementing sparse matrices will not solve this issue, and unless there is a faster computational way to obtain the same result, the performance will persist because it is arises from the NetworkX library. Your knowledge of Markov chains is probably deeper than mine, so if you know any procedural algorithm capable of detecting chain classes without using directed graphs, feel free to suggest them.

**Comment by Marius1311** [comment]
I'm not an expert today but I looked into it a bit and I found out that what we are looking for is called the 'strongly connected components' in graph theroy, and there is an algorithm that solves this in linear time: https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm

My feeling is that this should be fairly quick, even for large matrices, since it scales only linearly with the number of states.

**Comment by Marius1311** [comment]
I will check out whether we can use this algorithm directly and what we gain by doing so.

**Comment by TommasoBelluzzo** [comment]
Hi Marius, I'm wondering if you checked the algorithm above during your runs. I've read many performance comparisons concerning Python graphs recently, and it looks like the performance bottleneck comes from the fact that NetworkX backend is written in pure Python. In order to achieve a better overall performance, I think I should change my code so that it makes use of a C++ library based package like graph-tool.

**Comment by Marius1311** [comment]
Hi @TommasoBelluzzo , good to hear from you! In fact, I don't think NetworkX is the bottleneck - we run the following code on our data.

```python
di_graph = nx.DiGraph(T)
nx.strongly_connected_components(di_graph)
comm_classes = sorted(nx.strongly_connected_components(di_graph), key=len, reverse=True)
```
which identifies both transient as well as recurrent classes. This runs on ~18k nodes in about 1-2 min on my laptop. I think the bottleneck must be somewhere else.

**Comment by TommasoBelluzzo** [comment]
Hi Marius, I uploaded a slightly modified version of the class indices computation. For very big chains it's still slow, of course, but on my test environment it achieves a somewhat good performance improvement. Feel free to give it a try and tell me if you notice better performances too.

**Comment by Marius1311** [comment]
Thanks @TommasoBelluzzo !

**Comment by TommasoBelluzzo** [comment]
You’re welcome. I close this issue, but feel free to open a new one if the same issue occurs again or if you are not satisfied with the performance.
